### PR TITLE
Dashboard styles

### PR DESCRIPTION
**Pull request by AnthonyJCampbell**
# Description

Tweaking styles on the dashboard

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by Rexben001 — COMMENTED** [review]
Moses mentioned something like adding a view button on each farmer's record. 
It'd be nice if you guys can add the button

**Review by quansenB — APPROVED** [review]
Code looks good

**Comment by quansenB** [comment]
The fixed Statistics makes the farmer table almost unusable on mobile imo

**Review by quansenB — APPROVED** [review]

**Review by quansenB — CHANGES_REQUESTED** [review]
Make Statistics not fixed, breaks experience on mobile

**Comment by quansenB** [comment]
On my iPhone SE it stops scrolling the moment I stop tocuhing the screen. Thats not good UX especially for large datasets of farmers imo

**Comment by Pav0l** [comment]
Closing this one as the navbar/stats are taking up too much space on screen and do not provide for a good UX on mobile view.

**Pull request closed without merging**
