### PR TITLE
Enable Service Worker to allow offline functionality

### PR DESCRIPTION
**Pull request by daquinons**
# Description

create-react-app gives by a Service Worker that by default is disabled. I've enabled it in index.js and used the opportunity to move the serviceWorker to a better location ('utils' folder) and remove other default files that are not going to be used (css files, react svg logo, etc).
## Checklist

Remove any items which are not applicable.

- [X] I have performed a self-review of my own code

### CODE REVIEW

**Comment by daquinons** [comment]
[Enable Service Worker in React app](https://trello.com/c/dhtuRMFq/18-enable-service-worker-in-react-app)

**Comment by openwell** [comment]
Looks good

**Comment by Pav0l** [comment]
Easy change 🙂
Please make sure you document how it works in the PVD. If we're not sure about it yet, maybe we can merge it later.

**Comment by daquinons** [comment]
Thank you guys. I would say, let's merge it now because worst case scenario we only need to change .register() to .unregister() again if the solution is not what we expected when we actually have a real application to work with. 

Also, the request removes some of the boilerplate that we are not going to use, like the css files, react logo, etc (my bad because I should have not included it in this request) so it's important to have those changes in master for next cards ☺️

Let me know what you think

**Comment by daquinons** [comment]
I added the documentation about the PWA here https://www.notion.so/Architecture-1046220590914bbd9618415ca5bf05e6

**Pull request merged**
